# Generated by Django 4.1.7 on 2023-02-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_client_user_alter_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='cost',
            field=models.IntegerField(default=999999),
        ),
        migrations.AlterField(
            model_name='client',
            name='tier',
            field=models.CharField(blank=True, choices=[('1', 'First'), ('2', 'Second'), ('3', 'Third')], max_length=200),
        ),
    ]
